### ISSUE TITLE
Parser fails at Display Segments with reserved keyworks

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#18]
The Display Segment don't follow the standard lexical rules, it allows tokens not used anywhere else, such `@`(https://github.com/icicle-emu/icicle-emu/issues/14) and allow reserved keywords, such `call` constructor in [avr8](https://github.com/NationalSecurityAgency/ghidra/blob/0d71657d052743d37ccbf5eab0e9d4253529a3e7/Ghidra/Processors/Atmel/data/languages/avr8.sinc#L637)

This makes inspossible to parse the AVR8 CPU familly:
```
Unable to parse ghidra/Ghidra/Processors/Atmel/data/languages/avr8xmega.slaspec because:
avr8.sinc:637:1 error: Error parsing: Sleigh

:call abs22dst                   is phase=1 & (ophi7=0x4a & op1to3=0x7) ... & abs22dst {
 ^^^^^^
avr8.sinc:637:1 Error parsing: Item
avr8.sinc:637:1 Error parsing: Constructor
avr8.sinc:637:2 Unexpected token: Call (expected [])
```

**Comment by mchesser** [comment]
Reopening this since there are still issues related to `#` characters which will require some additional work.

**Comment by rbran** [comment]
I also had this problem and my solution was a little unconventional, I have basically two lexical parsers: normal/display.

The PreProcessor is a iterator like struct that produces token-normal and token-display, instead of reading the whole file creating a single token vector, we read/parse the file on the ast demand.

Buffering the tokens on the assertions level, like constructors parse-(normal/display) one token at the time until the `is` token is found, after that parse-normal  until `}` or `unimpl`, and then parse this created token vector using normal parsing techniques.

The PreProcessor parsing macros is separated from the regular lexer, it only uses the two lexers to produce tokens.

Something like this:
```mermaid
graph
subgraph AST builder
AST-->next_token_normal;
AST-->next_token_display;
subgraph PreProcessor and File Read
next_token_normal-->A{"@, $( or #"};
next_token_display-->B{"$("};
A-->|PROCESS|next_token_normal;
B-->|PROCESS|next_token_display;
A-->|NO|lexer_normal;
B-->|NO|lexer_display;
end
lexer_normal-->|token-normal|AST;
lexer_display-->|token-display|AST;
end
```

**Comment by mchesser** [comment]
Yeah I ended up with something similar in: 9aebe35
