### ISSUE TITLE
AARCH64BE is unable to parse adrp

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#26]
The AARCH64BE is unable to parse tokens `a0 03 00 90` into `adrp x0,0x74000`.

**Comment by mchesser** [comment]
Maybe I am missing something here -- but that seems to be the little endian encoding of [`adrp`](https://developer.arm.com/documentation/ddi0596/2021-09/Base-Instructions/ADRP--Form-PC-relative-address-to-4KB-page-). 

And flipping the bytes (i.e., to `90 00 03 a0` causes the instruction to be decoded correctly).

**Comment by rbran** [comment]
>Maybe I am missing something here -- but that seems to be the little endian encoding of adrp

That's exacly the problem, both LE and BE AARCH64 parse tokens in [little endian](https://github.com/NationalSecurityAgency/ghidra/blob/9ec89c37fb30d6228ed82d4cf1441b7a7aa0a3f1/Ghidra/Processors/AARCH64/data/languages/AARCH64instructions.sinc#L1019)

So, both `AARCH64` and `AARCH64BE` should be able to parse `90 00 03 a0` into `adrp`

**Comment by mchesser** [comment]
Ah, thanks for for mentioning that -- I didn't realize/forgot that token endianness could be overwritten in this way.

(Sorry for the delay reviewing your PRs -- I'll try to get to them soon).
