### ISSUE TITLE
Bitrange symbols are not handle

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#32]
This is known [issue](https://github.com/icicle-emu/icicle-emu/blob/75f0259dfb264e3ffd7d2ecd1f9ede3a9a65d9d9/sleigh/sleigh-compile/src/constructor/semantics.rs#L866).

**Comment by mchesser** [comment]
I'm currently doing a small rework to address this and #30

**Comment by rbran** [comment]
Great, will wait for that before trying to search and fix new bugs.
