### ISSUE TITLE
Non-comparison field in pattern OR statement.

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#38]
Any field that happen inside an OR constraint pattern that is not being compared to a value, is not being produced, it implies an comparison `!= 0`, like in C.

Example: https://github.com/NationalSecurityAgency/ghidra/blob/0beaf23e035a0e82fd737949b774f0a8a55f9e35/Ghidra/Processors/TI_MSP430/data/languages/TI430Common.sinc#LL797C67-L797C95

**Comment by rbran** [comment]
Actually not true, the value is not verified to be `!= 0`, the unrestrained value in a OR patterns must be some kind of "ordering forcing" mechanism, or a bug in the slaspec.

**Comment by rbran** [comment]
Just to be clear, in this context the `!= 0` makes sense to be enforced, it's just not what ghidra does.

**Comment by mchesser** [comment]
Thanks for looking into this.

I currently treat them as defining an operand/subtable -- however currently the code assumes all arms of of an OR pattern define the same operands/subtables (which is clearly not the case in that constructor). 

It probably makes sense to warn on this behavior and require writing `!= 0`

**Comment by rbran** [comment]
The reason why this behaviour is present at Ghidra will probably be at https://github.com/NationalSecurityAgency/ghidra/pull/5488 once closed.
