### ISSUE TITLE
JIT Compilation error when byte swapping i8 input

### ISSUE THREAD

**Issue by Benedict98ee** [icicle-emu/icicle-emu#44]
![Screenshot from 2023-07-28 09-52-50](https://github.com/icicle-emu/icicle-emu/assets/69200986/323a46af-b893-46a9-b594-1f13be3a0926)
![Screenshot from 2023-08-07 09-51-31](https://github.com/icicle-emu/icicle-emu/assets/69200986/0fe02072-2673-4899-8e64-51214c303942)

JIT Compiler error when attempting to byte swap 1 Byte input.

![Screenshot from 2023-08-07 09-53-50](https://github.com/icicle-emu/icicle-emu/assets/69200986/e9c112b2-922f-44e8-a7e4-5b751b75237b)

Cranelift generated bswap instruction

**Comment by mchesser** [comment]
Thanks, fixed.

I think this issue was introduced when I swapped from using my custom bswap implementation to the one in cranelift when it was added.

BE architectures could be better tested.
