### ISSUE TITLE
Question: Single function execution (Emulator)

### ISSUE THREAD

**Issue by VPaulV** [icicle-emu/icicle-emu#60]
Thank you for developing and open-sourcing this excellent tool!

Apologies for opening a new issue; however, I was unable to locate relevant documentation or code addressing my question. Is there a method to execute a specific function at a designated address rather than running the entire binary? Any guidance would be greatly appreciated.

**Comment by mchesser** [comment]
Yeah the documentation needs some work, but this should be fairly easy to do depending on your use case.

`vm.run` will execute from the current program counter, so to execute a specific function you load in the binary, set the pc to the start of the function (using `vm.cpu.write_pc(<address_of_function>)`), and set up the input arguments and stack pointer based on the calling convention. (The comment here has a more complete example: https://github.com/icicle-emu/icicle-emu/issues/52#issuecomment-1751660531) 

For fuzzing, there is a basic harness that lets you configure things using a config file. e.g., to run the function `base64_decode_ctx` within an Aarch64 base64 binary, you create a config like:

File: `base64.ron`

```ron
// _Bool base64_decode_ctx(base64_decode_context *ctx (x0),char *in (x1),size_t inlen (x2),char *out (x3),size_t *outlen (x4))
(
    hooks: {
        // 0x10000700: Crash,
        0x4018e0: Exit, // Exit the fuzzer at the `ret` instruction in `base64_decode_ctx`.
    },
    extra_memory: [
        // Memory to use for the stack and local variables.
        (offset: 0x20000000, size: 0x10000, perm: RW),

        // Memory to use for the input buffer
        (offset: 0x30000000, size: 0x100000, perm: R),

        // Memory to use for the output buffer
        (offset: 0x40000000, size: 0x100000, perm: RW),
    ],
    initialize: [
        (location: StartAddr, value: U64(0x00401430)), // Address of base64_decode_ctx
        (location: Reg("sp"), value: U64(0x20010000)), // stack pointer

        // decode_context* ctx (arg0)
        (location: Reg("x0"), value: U64(0x20000000)),
        // struct base64_decode_context { uint i, char[4] buf } = { 0 }`
        (location: Mem(0x20000000), value: U64(0)),
        (location: Mem(0x20000008), value: U64(0)),

        // char* in (arg1)
        (location: Reg("x1"), value: U64(0x30000000)), // Create pointer to mapped memory.
        (location: Mem(0x30000000), value: InputData), // Initialize memory using fuzzer data.

        // size_t inlen (arg3)
        (location: Reg("x2"), value: InputLength),

        // char* out (arg4)
        (location: Reg("x3"), value: U64(0x40000000)),

        // size_t* outlen (arg5)
        (location: Reg("x4"), value: U64(0x20000010)),
    ]
)
```

Then run it using: 
```
ICICLE_ARCH=aarch64-none ICICLE_CUSTOM_SETUP_PATH='base64.ron' afl-icicle-trace input-file -- /path/to/base64-aarch64
```


Or fuzz it using AFL/AFL++: 
```
ICICLE_ARCH=aarch64-none ICICLE_CUSTOM_SETUP_PATH='base64.ron' AFL_QEMU_CUSTOM_BIN=1 ../AFLplusplus/afl-fuzz -Q -t 1000+ -i inputs -o workdir afl-icicle-trace /path/to/base64-aarch64
```
